import sys, os, json, urllib.request
from playwright.sync_api import sync_playwright
T=open('/tmp/qa_t').read().strip() if os.path.exists('/tmp/qa_t') else sys.argv[1]
T=sys.argv[1]
D='qa/evidence/T-1acfb3b4db/'
U='http://localhost:4517'
def api(p): return json.load(urllib.request.urlopen(U+p))
with sync_playwright() as p:
    b=p.chromium.launch(); pg=b.new_page(viewport={'width':1200,'height':760})
    errs=[]; pg.on('pageerror',lambda e:errs.append(str(e)))
    pg.goto(U); pg.wait_for_selector('.tree-item')
    pg.screenshot(path=D+'01_initial.png')
    pg.click('#new-note'); pg.wait_for_selector('.tree-input')
    assert os.path.exists(T+'/A/Untitled.md')
    assert pg.evaluate("document.activeElement.className")=='tree-input'
    pg.screenshot(path=D+'02_new_note_rename.png')
    pg.keyboard.press('Control+a'); pg.keyboard.type('Renamed'); pg.keyboard.press('Enter')
    pg.wait_for_timeout(600)
    assert os.path.exists(T+'/A/Renamed.md') and not os.path.exists(T+'/A/Untitled.md')
    pg.click('#new-note'); pg.wait_for_timeout(500)
    assert os.path.exists(T+'/A/Untitled.md'); pg.keyboard.press('Escape'); pg.wait_for_timeout(300)
    pg.click('#new-note'); pg.wait_for_timeout(500)
    assert os.path.exists(T+'/A/Untitled 2.md'); pg.keyboard.press('Escape')
    pg.click('#new-folder'); pg.wait_for_selector('.tree-input'); pg.keyboard.type('Fresh'); pg.keyboard.press('Enter'); pg.wait_for_timeout(500)
    assert os.path.isdir(T+'/A/Fresh')
    pg.click('#sort'); print('sort title',pg.get_attribute('#sort','title'))
    pg.click('.tree-item:has-text("alpha")', button='right'); pg.wait_for_selector('.px-menu')
    pg.screenshot(path=D+'03_context_menu.png')
    pg.click('.px-menu-item:has-text("Rename")'); pg.wait_for_selector('.tree-input')
    pg.keyboard.press('Control+a'); pg.keyboard.type('gamma'); pg.keyboard.press('Enter'); pg.wait_for_timeout(600)
    assert os.path.exists(T+'/A/gamma.md')
    pg.click('.tree-item:has-text("gamma")'); pg.wait_for_timeout(400)
    pg.click('.tree-item:has-text("gamma")', button='right')
    pg.click('.px-menu-item:has-text("Move to")'); pg.wait_for_selector('.px-dialog')
    pg.screenshot(path=D+'04_move_dialog.png')
    pg.click('.px-row:has-text("sub")'); pg.click('.px-btn.primary'); pg.wait_for_timeout(700)
    assert os.path.exists(T+'/A/sub/gamma.md')
    print('tabs after move:', pg.inner_text('#tabs') if pg.query_selector('#tabs') else pg.inner_text('body')[:200])
    pg.click('.tree-item:has-text("gamma")', button='right'); pg.click('.px-menu-item:has-text("Delete")'); pg.wait_for_selector('.px-dialog')
    print('confirm:',pg.inner_text('.px-dialog-text'))
    pg.screenshot(path=D+'05_delete_confirm.png')
    pg.click('.px-btn.danger'); pg.wait_for_timeout(600)
    assert not os.path.exists(T+'/A/sub/gamma.md')
    pg.click('.tree-item:has-text("sub")', button='right'); pg.keyboard.press('Escape'); assert not pg.query_selector('.px-menu')
    pg.click('#open-folder'); pg.wait_for_selector('.px-dialog')
    pg.fill('.px-input', T+'/B'); pg.keyboard.press('Enter'); pg.wait_for_timeout(500)
    pg.screenshot(path=D+'06_picker.png')
    pg.click('.px-dialog-actions .primary'); pg.wait_for_timeout(800)
    assert pg.inner_text('#folder-name')=='B', pg.inner_text('#folder-name')
    assert pg.query_selector('.tree-item:has-text("beta")')
    pg.screenshot(path=D+'99_after_task.png')
    pg.click('#folder-settings'); pg.wait_for_timeout(300)
    pg.screenshot(path=D+'07_settings.png')
    print('errs',errs); assert not errs
    json.dump({"01_initial.png":"Folder A tree","02_new_note_rename.png":"New note with inline rename","03_context_menu.png":"Context menu","04_move_dialog.png":"Move dialog","05_delete_confirm.png":"Delete confirm","06_picker.png":"Folder picker","99_after_task.png":"After opening folder B","07_settings.png":"Settings panel"},open(D+'captions.json','w'))
    b.close()
print('OK')
